# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install transformers torch huggingface_hub

from huggingface_hub import login

login(token="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")

# Install necessary libraries
!pip install transformers requests

import requests
import json

api_token = "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"

headers = {
    "Authorization": f"Bearer {api_token}",
    "Content-Type": "application/json"
}

def generate_blog_content(product_details, min_words=1500):
    model_name = "mistralai/Mistral-7B-Instruct-v0.3"
    prompt = """
    Input: Product: {product_details}
    Task: Write a blog about trendy topics related to the business idea. The blog should have the following structure:

    Title: A catchy and engaging title related to the product.

    Subtitle: A relevant and interesting subtitle highlighting the product's key benefits or unique features.

    Introduction: Provide a brief introduction to the product, explaining its significance and why it stands out in the market. Mention the product's primary purpose and its appeal to the target audience.

    Main Body:
    - **Section 1: **
      Describe the product's design and aesthetics. Highlight the materials used, the overall look, and how these contribute to its functionality. Explain the audio technology and features that enhance sound quality, such as drivers, magnets, or diaphragms.

    - **Section 2: **
      Discuss how the product fits into daily life and its practical applications. Focus on aspects like comfort, usability, and any features that make it suitable for specific activities or environments, such as commuting or exercising.

    - **Section 3: **
      Explore additional features that add value to the product. This could include built-in functionalities, controls, or any other enhancements that improve user experience. Explain how these features address user needs or offer convenience.

    Conclusion: Summarize the key points discussed in the blog. Reinforce the product's strengths and benefits. End with a call to action, encouraging readers to consider purchasing or learning more about the product.

    """

    generated_text = ""

    while len(generated_text.split()) < min_words:
        payload = {
            "inputs": prompt + " " + generated_text,
            "parameters": {
                "max_length": 2000,
                "temperature": 0.7,
                "top_k": 50,
                "top_p": 0.95,
                "repetition_penalty": 1.2,
                "no_repeat_ngram_size": 3,
                "num_return_sequences": 1,
                "early_stopping": True,
            }
        }

        response = requests.post(
            f"https://api-inference.huggingface.co/models/{model_name}",
            headers=headers,
            data=json.dumps(payload)
        )

        if response.status_code == 200:
            response_data = response.json()
            new_text = response_data[0]["generated_text"]
            if not new_text.strip() or len(new_text.split()) == 0:
                break
            generated_text += " " + new_text
        else:
            raise Exception(f"Request failed with status code {response.status_code}, response: {response.text}")

    return generated_text.strip()

user_input = "Samsung wireless earphones"

generate_blog_content(user_input)